### ISSUE TITLE
Exception at setup: Invalid cross-device link

### ISSUE THREAD

**Issue by phipolis** [hyPiRion/inlein#21]
Having a snag with the first run setup on a Fedora 25 system. On Fedora, /tmp is mounted on tmpfs, so /home is on a separate partition from it. 
```
Exception in thread "main" java.nio.file.AtomicMoveNotSupportedException: /tmp/inlein-daemon-0.1.0-standalone.jar3337533130092798241.jar -> /home/phip/.inlein/daemons/inlein-daemon-0.1.0-standalone.jar: Invalid cross-device link
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:394)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at inlein.client.Utils.downloadFile(Utils.java:33)
	at inlein.client.tasks.Upgrade.downloadDaemon(Upgrade.java:68)
	at inlein.client.ServerConnection.tryDownload(ServerConnection.java:61)
	at inlein.client.ServerConnection.tryStart(ServerConnection.java:37)
	at inlein.client.ServerConnection.ensureConnected(ServerConnection.java:24)
	at inlein.client.tasks.Run.run(Run.java:23)
	at inlein.client.Main.main(Main.java:32)
```

**Comment by hyPiRion** [comment]
Sorry for the delay here, this was fixed in #6 and should work as expected on the master branch.
