### ISSUE TITLE
Problem with different mount points

### ISSUE THREAD

**Issue by whilo** [hyPiRion/inlein#5]
I get an error for an invalid link over device boundaries (or mount points). My home folder is mounted with ecryptfs while the /tmp is mounted seperately. I guess you are using hard links?

➜  ~ ./test_inlein.clj 
Downloading https://github.com/hyPiRion/inlein/releases/download/0.1.0/inlein-daemon-0.1.0-standalone.jar...
Exception in thread "main" java.nio.file.AtomicMoveNotSupportedException: /tmp/inlein-daemon-0.1.0-standalone.jar4290417000257353962.jar -> /home/void/.inlein/daemons/inlein-daemon-0.1.0-standalone.jar: Ungültiger Link über Gerätegrenzen hinweg
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:389)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1347)
	at inlein.client.Utils.downloadFile(Utils.java:33)
	at inlein.client.tasks.Upgrade.downloadDaemon(Upgrade.java:68)
	at inlein.client.ServerConnection.tryDownload(ServerConnection.java:61)
	at inlein.client.ServerConnection.tryStart(ServerConnection.java:37)
	at inlein.client.ServerConnection.ensureConnected(ServerConnection.java:24)
	at inlein.client.tasks.Run.run(Run.java:23)
	at inlein.client.Main.main(Main.java:32)

**Comment by hyPiRion** [comment]
Yeah, it seems like adding the `ATOMIC_MOVE` option fails as it tries to do a rename on the file, which fails because of the device boundary. 

I'm guessing that would be easy to fix by just removing the `ATOMIC_MOVE` option here:
https://github.com/hyPiRion/inlein/blob/b87acc814c5d832f48352bceb9190d10e50cdffd/client/src/inlein/client/Utils.java#L33-L34

In the meantime, as a short fix, you should be able to get inlein up and running by doing

```
curl -L https://github.com/hyPiRion/inlein/releases/download/0.1.0/inlein-daemon-0.1.0-standalone.jar -o /home/void/.inlein/daemons/inlein-daemon-0.1.0-standalone.jar
```

or

```
wget -O /home/void/.inlein/daemons/inlein-daemon-0.1.0-standalone.jar https://github.com/hyPiRion/inlein/releases/download/0.1.0/inlein-daemon-0.1.0-standalone.jar
```

**Comment by arrdem** [comment]
I got bitten by this as well

**Comment by whilo** [comment]
@hyPiRion thanks, that fixed it.

**Comment by soulawaker** [comment]
I've got same problem.
need to change 'inlein' file in release section, which is linked in README, for newbie like me.
It might not be removed ATOMIC_MOVE.

**Comment by hyPiRion** [comment]
Yeah, sorry about this, there hasn't been a release with this one shipped yet.

**Comment by soulawaker** [comment]
@hyPiRion 
If I could upload inlein file to release section, I would do it for contributing. Thanks for your works!
